version: '3.8'
name: 'join'

services:
  join:
    container_name: join
    build: 
      context: ./
    environment:
      - DATABASE_URL=file:/app/db/dev.db    ## SQLITE PATH
      - ORIGIN=http://127.0.0.1:3000    ## IMPORTANT
      - PORT=3000
    volumes:
      - ./join_db/:/app/db   ## to mount db locally
    ports:
      - 3000:3000
    restart: always
    # depends_on:
    #   - db
  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: join_db
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - db_data:/var/lib/mysql
  #     #- ./db/join_db.sql:/docker-entrypoint-initdb.d/join_db.sql
  #   healthcheck:
  #     test: ['CMD', 'join_db', 'ping', '-h', 'localhost']
  #     interval: 20s
  #     timeout: 5s
  #     retries: 10